// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bison.Razor.Migrations
{
    [DbContext(typeof(BisonDBContext))]
    partial class BisonDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Bison.Razor.Models.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Bison.Razor.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Post");

                    b.HasDiscriminator().HasValue("Post");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Bison.Razor.Models.Taxon", b =>
                {
                    b.Property<string>("TaxonId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DanishVernacularName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("parentTaxonId")
                        .HasColumnType("TEXT");

                    b.HasKey("TaxonId");

                    b.HasIndex("parentTaxonId");

                    b.ToTable("taxons");
                });

            modelBuilder.Entity("Bison.Razor.Models.Comment", b =>
                {
                    b.HasBaseType("Bison.Razor.Models.Post");

                    b.Property<int>("ObservationId")
                        .HasColumnType("INTEGER");

                    b.HasIndex("ObservationId");

                    b.HasDiscriminator().HasValue("Comment");
                });

            modelBuilder.Entity("Bison.Razor.Models.Observation", b =>
                {
                    b.HasBaseType("Bison.Razor.Models.Post");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TaxonId")
                        .HasColumnType("TEXT");

                    b.HasIndex("TaxonId");

                    b.HasDiscriminator().HasValue("Observation");
                });

            modelBuilder.Entity("Bison.Razor.Models.Proposal", b =>
                {
                    b.HasBaseType("Bison.Razor.Models.Post");

                    b.Property<int>("ObservationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaxonId")
                        .HasColumnType("TEXT");

                    b.HasIndex("ObservationId");

                    b.HasIndex("TaxonId");

                    b.ToTable("Post", t =>
                        {
                            t.Property("ObservationId")
                                .HasColumnName("Proposal_ObservationId");

                            t.Property("TaxonId")
                                .HasColumnName("Proposal_TaxonId");
                        });

                    b.HasDiscriminator().HasValue("Proposal");
                });

            modelBuilder.Entity("Bison.Razor.Models.Post", b =>
                {
                    b.HasOne("Bison.Razor.Models.Author", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Bison.Razor.Models.Taxon", b =>
                {
                    b.HasOne("Bison.Razor.Models.Taxon", "parent")
                        .WithMany("children")
                        .HasForeignKey("parentTaxonId");

                    b.Navigation("parent");
                });

            modelBuilder.Entity("Bison.Razor.Models.Comment", b =>
                {
                    b.HasOne("Bison.Razor.Models.Observation", "Observation")
                        .WithMany("Comments")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Observation");
                });

            modelBuilder.Entity("Bison.Razor.Models.Observation", b =>
                {
                    b.HasOne("Bison.Razor.Models.Taxon", "Taxon")
                        .WithMany()
                        .HasForeignKey("TaxonId");

                    b.Navigation("Taxon");
                });

            modelBuilder.Entity("Bison.Razor.Models.Proposal", b =>
                {
                    b.HasOne("Bison.Razor.Models.Observation", "Observation")
                        .WithMany("Proposals")
                        .HasForeignKey("ObservationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Bison.Razor.Models.Taxon", "taxon")
                        .WithMany()
                        .HasForeignKey("TaxonId");

                    b.Navigation("Observation");

                    b.Navigation("taxon");
                });

            modelBuilder.Entity("Bison.Razor.Models.Author", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Bison.Razor.Models.Taxon", b =>
                {
                    b.Navigation("children");
                });

            modelBuilder.Entity("Bison.Razor.Models.Observation", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Proposals");
                });
#pragma warning restore 612, 618
        }
    }
}
